version: "3"

networks:
  saarm-network:
    driver: bridge
    ipam:
      config:
        - subnet: ${DOCKER_SUBNET}

services:
  saarm_go:
    image: "golang:1.21.5-alpine"
    container_name: saarm_go
    working_dir: /app
    entrypoint: ["sh", "./start.sh"]
    restart: always
    ports:
      - ${APP_ENV_HOST}:8000
    environment:
      - APP_ENV_POSTGRESQL_HOST=${APP_ENV_POSTGRESQL_HOST}
      - APP_ENV_POSTGRESQL_PORT=${APP_ENV_POSTGRESQL_PORT}
      - APP_ENV_POSTGRESQL_USERNAME=${APP_ENV_POSTGRESQL_USERNAME}
      - APP_ENV_POSTGRESQL_PASSWORD=${APP_ENV_POSTGRESQL_PASSWORD}
      - APP_ENV_POSTGRESQL_DATABASE=${APP_ENV_POSTGRESQL_DATABASE}
    volumes:
      - .:/app
    networks:
      - saarm-network
