version: "3"

networks:
  saarm-network:
    driver: bridge
    ipam:
      config:
        - subnet: ${DOCKER_SUBNET}

services:
  minio:
    image: "bitnami/minio:2024.4.6"
    container_name: ${MINIO_CONTAINER_NAME}
    restart: always
    ports:
      - ${MINIO_CONSOLE_PORT}:${MINIO_CONSOLE_PORT}
      - ${MINIO_SERVER_PORT}:${MINIO_SERVER_PORT}
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
      - MINIO_SERVER_ACCESS_KEY=${MINIO_SERVER_ACCESS_KEY}
      - MINIO_SERVER_SECRET_KEY=${MINIO_SERVER_SECRET_KEY}
    volumes:
      - ./volumes/minio-data:/bitnami/minio/data

  db:
    image: "bitnami/postgresql:16"
    container_name: saarm_db
    restart: always
    ports:
      - ${POSTGRES_PORT}:5432
    environment:
      - POSTGRESQL_USERNAME=${POSTGRES_USERNAME}
      - POSTGRESQL_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRESQL_DATABASE=${POSTGRES_DATABASE}
    volumes:
      - ./volumes/pg-data:/bitnami/postgresql
      - /etc/localtime:/etc/localtime:ro
    networks:
      - saarm-network
