version: '3'

networks:
  saarm-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.28.0.0/16

services:
  saarm_db:
    image: 'bitnami/postgresql:16'
    container_name: saarm_db
    restart: always
    ports:
      - 5400:5432
    environment:
      - POSTGRESQL_HOST=172.28.0.1
      - POSTGRESQL_USERNAME=tientran
      - POSTGRESQL_PASSWORD=tien123@
      - POSTGRESQL_DATABASE=saarm_db
    volumes:
      - ./volumes/:/bitnami/postgresql
      - /etc/localtime:/etc/localtime:ro
    networks:
      - saarm-network

  saarm_go:
    image: 'golang:1.21.5-alpine'
    container_name: saarm_go
    working_dir: /app
    entrypoint: ['sh', './start.sh']
    restart: always
    ports:
      - 8000:8000
    environment:
      - APP_ENV_POSTGRESQL_HOST=172.28.0.1
      - APP_ENV_POSTGRESQL_PORT=5400
      - APP_ENV_POSTGRESQL_USERNAME=tientran
      - APP_ENV_POSTGRESQL_PASSWORD=tien123@
      - APP_ENV_POSTGRESQL_DATABASE=saarm_db
    volumes:
      - .:/app
    networks:
      - saarm-network
